(defun sweyla897401 ()
  "Theme generated by Sweyla: http://sweyla.com/themes/seed/897401/"
  (interactive)
  (color-theme-install
   '(sweyla897401
     ((background-color . "#00070A")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#A15200"))))
     (font-lock-constant-face ((t (:foreground "#D96A00"))))
     (font-lock-builtin-face ((t (:foreground "#7E4C6B"))))
     (font-lock-function-name-face ((t (:foreground "#CE1343"))))
     (font-lock-variable-name-face ((t (:foreground "#F52C7F"))))
     (font-lock-keyword-face ((t (:foreground "#B14876"))))
     (font-lock-string-face ((t (:foreground "#677F8C"))))
     (font-lock-doc-string-face ((t (:foreground "#677F8C"))))
     (font-lock-type-face ((t (:foreground "#FF082F"))))
     )))

(provide 'sweyla897401)